### ISSUE TITLE
Amazfit account : Client Error: Unauthorized for url: https://account.huami.com/v2/client/login

### ISSUE THREAD

**Issue by ncartron** [argrento/huami-token#18]
Hi and thanks for this nice initiative.

I wanted to get the BT keys as well as AGPS files from a Stratos 3, but using huami-token from MacOS gives me this error:

```
➜ ./huami_token.py -m amazfit -e "myemail@domain.tld" -p "redacted" --bt_keys
Getting access token with amazfit login method...
Token: ['redacted']
Logging in...
Traceback (most recent call last):
  File "./huami_token.py", line 252, in <module>
    device.login()
  File "./huami_token.py", line 104, in login
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://account.huami.com/v2/client/login
```

I confirmed that the email address and password are correct - that's the ones i used when connecting using the Amazfit / Zepp app on Android.

Any idea?

Thanks!
Nico

**Comment by argrento** [comment]
Hello! 

I am not sure, how Stratos 3 AGPS data is downloaded, because I have no Stratos watch. I will add this to the project readme.

Sorry for the inconvenience.

**Comment by ncartron** [comment]
Hi @argrento and thanks for the answer.
I don't think the issue I'm encountering is because of the watch - I had created my Amazfit account before, when I had a GTS.

**Comment by argrento** [comment]
Are you using VPN or proxy on your PC?

**Comment by ncartron** [comment]
I am not 

-- 
Nico

**Comment by argrento** [comment]
Have you tried logging in via Xiaomi account? 
https://github.com/argrento/huami-token#logging-in-with-xiaomi-account

**Comment by ncartron** [comment]
I have not, since I only have an Amazfit account, and my Stratos 3 is registered with that account, not a Xiaomi one :)

**Comment by 8ear** [comment]
Do you use an internal account?
I used an google account instead of internal and it looks that it does not work for me.
So I think the problem here is that I do not use the internal amazfit authentication.
