### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by jaum20** [argrento/huami-token#25]
Hi, I'm having [this same problem](https://github.com/argrento/huami-token/issues/22), but the solution didn't worked for me. I downloaded Zepp app and could not login using mu xiaomi account credentials. So, I created a Zepp account using the same email and password but the problem persists

```
py huami_token.py --method xiaomi --email xxxxxx@gmail.com --password xxxxxxx--bt_keys
Getting access token with xiaomi login method...
Copy this URL to web-browser

https://account.xiaomi.com/oauth2/authorize?skip_confirm=false&client_id=xxxxxxxx

and login to your Mi account.

Paste URL after redirection here.
https://hm.xiaomi.com/watch.do?code=ALSG_CLOUDSRV_xxxxxxxxxx
Token: ['ALSG_CLOUDSRV_xxxxxxxxx']
Logging in...
Traceback (most recent call last):
  File "C:\Users\xxxxx\huami-token\huami_token.py", line 265, in <module>
    device.login()
  File "C:\Users\xxxxxx\huami-token\huami_token.py", line 116, in login
    raise ValueError(f"Login error. Error: {login_result['error_code']}")
ValueError: Login error. Error: 0117


```

**Comment by argrento** [comment]
Hi!

**Comment by jaum20** [comment]
Thank you and sorry for any inconvenience
