### ISSUE TITLE
Xiaomi login fails

### ISSUE THREAD

**Issue by W-Floyd** [argrento/huami-token#3]
Has the procedure changed at all?

```
Getting access token with xiaomi login method...
Copy this URL to web-browser 

https://account.xiaomi.com/oauth2/authorize?skip_confirm=false&client_id=XXXXXXXXX&pt=0&scope=1+6000+16001+20000&redirect_uri=https%3A%2F%2Fhm.xiaomi.com%2Fwatch.do&_locale=en_US&response_type=code

and login to your Mi account.

Paste URL after redirection here.
https://hm.xiaomi.com/watch.do?code=ALSG_CLOUDSRV_XXXXXXXXXXXXXXXXXXXXXXXXX
Token: ['ALSG_CLOUDSRV_XXXXXXXXXXXXXXXXXXXXXXXXXXXX]
Logging in...
Traceback (most recent call last):
  File "huami_token.py", line 222, in <module>
    device.login()
  File "huami_token.py", line 106, in login
    raise ValueError(f"Login error. Error: {login_result['error_code']}")
ValueError: Login error. Error: 0117
```

**Comment by argrento** [comment]
Just tested with my login cridentials, all was fine. Error 0117 stands for ACCOUNT_NOT_REGISTER error.

**Comment by W-Floyd** [comment]
Perhaps it's an issue with my band being linked to my Google login, though I ran the tool with me actual Xiaomi account. I'll reopen if that isn't the case.

**Comment by W-Floyd** [comment]
This was indeed the case. Sorry for the confusion.
