### ISSUE TITLE
Login step for Xiaomi method failing

### ISSUE THREAD

**Issue by johnnymck** [argrento/huami-token#32]
When running `python huami_token.py --method xiaomi --bt_keys` and following the instructions in `README.md`, after the copying and pasting the redirect URL into the terminal, I get the following error: 

```Logging in...
Traceback (most recent call last):
  File "huami_token.py", line 352, in <module>
    device.login()
  File "huami_token.py", line 141, in login
    raise ValueError(f"Login error. Error: {login_result['error_code']}")
ValueError: Login error. Error: 0117```

If this is an error on my end, I'll be glad to best figure out how to solve this :)

**Comment by argrento** [comment]
This error stand for `AUTH_SERVER_ERROR_ACCOUNT_NOT_REGISTER`. Try this: https://github.com/argrento/huami-token/issues/22#issuecomment-733890511

**Comment by johnnymck** [comment]
I'll give this a go, thanks :)

**Comment by johnnymck** [comment]
Tried linking with Zepp, then trying the amazfit login. Worked a treat, TYSM. Might want to add a note to this effect on the readme?

Cheers and all the best.
