### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by snjyr123** [argrento/huami-token#44]
Traceback (most recent call last):
  File "huami_token.py", line 35, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

This error pops up whenever I type in my credentials into powershell for getting the key.

**Comment by snjyr123** [comment]
Fixed the error by installing requests for python and every other dependency I am still getting the error no module named rich, even though I installed it.

**Comment by snjyr123** [comment]
> try this `pip install requests` and this `pip install rich`

still getting the error :(

**Comment by snjyr123** [comment]
tried installing rich manually as well...

**Comment by snjyr123** [comment]
Traceback (most recent call last):
  File "huami_token.py", line 36, in <module>
    from rich import box
ModuleNotFoundError: No module named 'rich'

**Comment by snjyr123** [comment]
I just ended up using Ubuntu and downloading it and it worked real quick, thx for all of your help though!
