### ISSUE TITLE
please,help me fix it!!!!

### ISSUE THREAD

**Issue by hgjl-mongol** [argrento/huami-token#53]
huami-token-master> python huami_token.py --method xiaomi --bt_keys

Getting linked wearables...
Traceback (most recent call last):
  File "F:\小米手环\huami-token-master\huami-token-master\huami_token.py", line 356, in <module>
    wearables = device.get_wearables()
  File "F:\小米手环\huami-token-master\huami-token-master\huami_token.py", line 190, in get_wearables
    raise ValueError("No 'auth_key' parameter in device data.")
ValueError: No 'auth_key' parameter in device data.

**Comment by hgjl-mongol** [comment]
Please tell me the solution

**Comment by argrento** [comment]
Which devices do you have in the your account?
