### ISSUE TITLE
Login error. Error: 0117. Account not registered.

### ISSUE THREAD

**Issue by heuwerk** [argrento/huami-token#66]
I get the error message mentioned in the title when trying to log in with my Xiaomi account.

The account exists and I can log in with it.

Can you help me further?

Error Log:
```python
Logging in...
Traceback (most recent call last):
  File "/home/user/git/huami-token/huami_token.py", line 353, in <module>
    device.login()
  File "/home/user/git/huami-token/huami_token.py", line 144, in login
    raise ValueError(f"Login error. Error: {error_message}")
ValueError: Login error. Error: 0117. Account not registered.
```

**Comment by heuwerk** [comment]
Sorry, I will try this workaround first: https://github.com/argrento/huami-token/issues/22#issuecomment-733890511

**Comment by heuwerk** [comment]
Unfortunately, this workaround did not bring any improvement either.

I can now log in, but I do not get any devices as output.

I own a Xiaomi Mi Smart Band 6 with firmware v1.0.6.16

**Comment by Zzywdl** [comment]
Just stop in the web page and copy and paste the code to your Python3ide application you will get that new code. If you still confused i advice you do it from step one&nbsp;


Hope you success
https://youtu.be/hY_zMnlfuCU



发自我的iPhone


------------------ Original ------------------
From: heuwerk ***@***.***&gt;
Date: Mon,Jun 27,2022 1:01 AM
To: argrento/huami-token ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [argrento/huami-token] Login error. Error: 0117. Account notregistered. (Issue #66)





 
I get the error message mentioned in the title when trying to log in with my Xiaomi account.
 
The account exists and I can log in with it.
 
Can you help me further?
 
Error Log:
 Logging in... Traceback (most recent call last):   File "/home/user/git/huami-token/huami_token.py", line 353, in <module&gt;     device.login()   File "/home/user/git/huami-token/huami_token.py", line 144, in login     raise ValueError(f"Login error. Error: {error_message}") ValueError: Login error. Error: 0117. Account not registered.
